name: Deploy Strapi to Oracle Cloud

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: strapi-app
  OCI_SSH_USER: ubuntu
  DATABASE_CA_FILE: ca.pem

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare deployment files
        run: |
          echo "${{ secrets.DATABASE_CA_CERT }}" > ${{ env.DATABASE_CA_FILE }}
          echo "DATABASE_CLIENT=postgres" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_SSL=true" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.OCI_PUBLIC_IP }}
          username: ${{ env.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            # Create required directories
            sudo mkdir -p /strapi/{config,uploads,tmp}
            sudo chown -R 1001:1001 /strapi
            
            # Transfer files
            echo "${{ secrets.DATABASE_CA_CERT }}" > /tmp/ca.pem
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # Stop and remove old container
            docker stop strapi || true
            docker rm strapi || true
            
            # Pull new image
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
            
            # Run new container
            docker run -d \
              --name strapi \
              --restart unless-stopped \
              -p 1337:1337 \
              -v /strapi/config:/app/config \
              -v /strapi/uploads:/app/public/uploads \
              -v /strapi/tmp:/app/.tmp \
              -v /tmp/ca.pem:/app/ca.pem \
              --env-file .env \
              ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
            
            # Cleanup
            rm /tmp/ca.pem

      - name: Cleanup
        run: |
          rm -f ${{ env.DATABASE_CA_FILE }} .env