name: Deploy Strapi to Oracle Cloud

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t strapi-app .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag strapi-app ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into Oracle Cloud Instance and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.OCI_PUBLIC_IP }}  # Use your Oracle instance's public IP
          username: ubuntu  # Change if necessary
          key: ${{ secrets.OCI_PRIVATE_KEY }}  # Store the private key securely in GitHub Secrets
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest
            docker stop strapi-app || true
            docker rm strapi-app || true
            docker run -d --name strapi-app -p 1337:1337 ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest
